### ISSUE TITLE
[BUG] Script error

### ISSUE THREAD

**Issue by MildlyInterested** [TMZulu/ZHC#11]
**Describe the bug**
Script Error in logs`, doesn't seem to affect functionality. 

**To Reproduce**
Spawn OPFOR and BLUEFOR units, let them fight.

**Expected behavior**
No script errors.

**Mods loaded at the time**
CBA
ACE
ZHC

**Additional context**
Can send whole RPT if needed

```12:12:16 Error in expression <gClient", (zhc_offload_ZeusArray select _dataIndex), true];
} else {
_groupMovin>
12:12:16   Error position: <_dataIndex), true];
} else {
_groupMovin>
12:12:16   Error Undefined variable in expression: _dataindex
12:12:16 File t\zhc\addons\offload\fnc_zeusTransfer.sqf..., line 86
12:12:16 Error in expression <oupMoving, zhc_offload_ZeusArray select _dataIndex]);
zhc_offload_ZeusHeldUnitCo>
12:12:16   Error position: <_dataIndex]);
zhc_offload_ZeusHeldUnitCo>
12:12:16   Error Undefined variable in expression: _dataindex
12:12:16 File t\zhc\addons\offload\fnc_zeusTransfer.sqf..., line 82
```

**Comment by TMZulu** [comment]
Can you please provide the full RPT though a pastebin or similar source please? There Is likely something else in the RPT related to this error that is that actual cause. 

Additionally, was the Zeus player given Zeus after loading in or was there a GM module already attached to the slot they loaded in?

**Comment by MildlyInterested** [comment]
Mission was barebones with only one player placed down, one HC module and respawn enabled. Zeus access was gained through ACE zeus.


[arma3server_x64_2021-05-30_11-45-39.log](https://github.com/TMZulu/ZHC/files/6571740/arma3server_x64_2021-05-30_11-45-39.log)
