### ISSUE TITLE
[FEATURE] Option To Exclude Specific Unit Classes From Transfers

### ISSUE THREAD

**Issue by Kharos6** [TMZulu/ZHC#19]
**Is your feature request related to a problem? Please describe.**
I've noticed that AI units from mods with unique unit types (such as melee units from "Improved Melee System" and any anomaly/zombie mod units) stop functioning (moving or attacking) after they've been transferred to headless clients. 

I figure this is because those units have scripts that run on the zeus/server machine when they're spawned. Since those scripts do not get re-checked or transferred over to the headless client, the headless client doesn't know what to do with them. It's essentially the same thing that happens if you give a regular unit a waypoint before headless client transfer: the waypoint disappears after the transfer is done.

**Describe the solution you'd like**
An exclusion/blacklist system in the CBA options menu that would allow the user to list specific unit classes/types that should be excluded from being transferred to headless clients. So far I've tried to use the "Zeus Holding" system, but it becomes tedious to do so for every new group you spawn in Zeus.

**Describe alternatives you've considered**
I don't really know what else would be a practical solution without breaking something... so sadly I think that's it. I hope this is something that can be done!

Edit for urther clarification: not to be confused with variables, I'm talking about unit classes like: **B_RangeMaster_F** for example.

**Comment by TMZulu** [comment]
Hello, This feature is already present in the current blacklisting system. You can input entire or partial classnames into it. Any unit or vehicle that contains the classname(s) in them will be blacklisted from the system. 

Here is the code containing this if you wish to look further: https://github.com/TMZulu/ZHC/blame/master/addons/offload/fnc_checkBad.sqf#L45

**Comment by Kharos6** [comment]
Hey!

My apologies... for some reason while I was looking around the options in addon settings on my client I couldn't see that setting, only the regular blacklisted variable names list.

I checked on my server now and it's there. An isolated incident I guess.

Thanks!

**Comment by TMZulu** [comment]
All good, no worries.
