### ISSUE TITLE
[FEATURE] log FPS and AI count to RPT

### ISSUE THREAD

**Issue by MildlyInterested** [TMZulu/ZHC#2]
Have an option to output server fps, server group count and server ai count to log file (same data as shown on map).
Same for the headless clients, ideally all into the log file of the server.

Two options would be nice:
1. Easy readable
Basically output something like this to log file:
```Server FPS: %1, Server groups: %2, Server units: %3, HC1 FPS: %4, HC1 groups: %5 and so on.```

***
2. CSV friendly
Output like this:
Init line:
```;"unique identifier so export out of log file";server_fps;server_grp;server_units;hc1_fps;hc1_grp;hc1_units;....```
the first semicolon is there so you have a nice column of server time.
Following lines just being this:
```;"unique identifier so export out of log file";%1,%2,....```

**Comment by TMZulu** [comment]
Not sure if I want to have them all printed into server RPT as that will require that data to be sent repeatedly to the server from all the HCs. It may be best to print this data into each one's respective RPT. This is how the monitor system works currently. Each one manages its own display/marker. 

The information will just be in each one's respective rpt which may actually be better for handling.

**Comment by MildlyInterested** [comment]
Hmm, yeah its definitely easier to code, simply adding a diag_log text option to the FPS script.
If you wanna take a look at how you could log it all on the server you can take a look a the script I altered a bit (which also logs player FPS and sends it to server): https://github.com/MildlyInterested/Arma3-Stuff/blob/main/Player_HCs_Server_FPS_Logging/scripts/FPS_Monitor.sqf

I don't think the data being send from the HC should affect much since ideally they're all on the same machine. My script even sends player data every 20 seconds and I couldn't see a performance impact.
