### ISSUE TITLE
[FEATURE] Blacklist for Vehicles

### ISSUE THREAD

**Issue by SekiAlpha** [TMZulu/ZHC#21]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
In my case, I'd like to blacklist mortars and artillery since I noticed that the artillery fire mission module that comes with Zeus Enhanced doesn't seem to work properly 100% of the time if the AI is on headless clients.

**Describe the solution you'd like**
I'd like to be able to blacklist certain vehicles or maybe have the option to blacklist all AI in vehicles. The reason why I say all vehicles is because in the past I've noticed that headless clients do not operate very well when they control vehicles.

**Describe alternatives you've considered**
I have considered just blacklisting the unit type that occupies said vehicles, however, I have no idea how I can automate the retrieval of all the class names I need. I think it would be much easier, however still very tedious to black list vehicle class names. That being said if there is an easy way to select the class names for all mortar, artillery, and helicopter units, then I will gladly use that option.

**Additional context**

No additional context.

**Comment by TMZulu** [comment]
You can blacklist the types for the mortars and arty themselves. Or you can use the Zeus Hold key to hold the units on your end so they don’t get transferred. If you wish to just blacklist, you can get any class names you want easily by placing the objects in editor and using the log section in the right click menu to copy its class name to clipboard. Here’s a guide: https://steamcommunity.com/sharedfiles/filedetails/?id=1341112604

**Comment by SekiAlpha** [comment]
So the way that the blacklist is currently implemented, will it be able to distinguish vehicle types or only the type of unit?

**Comment by TMZulu** [comment]
Both, the system will check both the unit type as well as if they are in a vehicle.
