### ISSUE TITLE
[BUG] AI transfer doesn't work after headless client disconnect

### ISSUE THREAD

**Issue by SekiAlpha** [TMZulu/ZHC#36]
**Describe the bug**
The code loop that transfers AI completely breaks after a headless client disconnects.

**To Reproduce**

Connect to a server with ZHC and at least 2 headless clients
Spawn some AI in
Wait for them to transfer
Disconnect one headless client
Observe no more AI groups are being transferred to headless clients.

**Expected behavior**
After disconnect, the untransfered AI get transferred to the remaining headless clients.

**Screenshots**

**Mods loaded at the time**
CBA
Please provide a list of mods leaded at the time.

**Additional context**

**Comment by TMZulu** [comment]
Fixed with MR #35
