### ISSUE TITLE
[BUG] RPT shows zhc_dynsim not found and HCs stop transfering

### ISSUE THREAD

**Issue by SekiAlpha** [TMZulu/ZHC#38]
**Describe the bug**
Randomly in the last 3 weeks, I've seen the ZHC mod break and stop transferring headless clients.

**To Reproduce**

There are no clear steps to reproduce the issue it just randomly occurs.

**Expected behavior**

Headless clients to keep transferring until mission end.

**Screenshots**

**Mods loaded at the time**
CBA
Please provide a list of mods leaded at the time.
'@ace'
	'@ACE Compat - RHS AFRF'
	'@ACE Compat - RHS- GREF'
	'@ACE Compat - RHS USAF'
	'@ACE Compat - RHS- SAF'
	'@BackpackOnChest - Redux'
	'@Breach'
	'@Canadian Forces Base Moosehead'
	'@Canadian_SOF_LITE_mas'
	'@CBA_A3'
	'@Ctab Devastator Edition'
	'@CUP Terrains - Core'
	'@CUP Terrains - CWA'
	'@CUP Terrains - Maps'
	'@CUP Weapons'
	'@CUP Vehicles'
	'@CUP Units'
	'@CUP ACE3 Compatibility Addon - Terrains'
	'@CUP ACE3 Compatibility Addon - Vehicles'
	'@CUP ACE3 Compatibility Addon - Weapons'
	'@Enhanced Movement'
	'@Enhanced Movement Rework'
	'@FIR AWS(AirWeaponSystem)'
	'@Hatchet Framework - Stable Version'
	'@Hatchet H-60 pack - Stable Version'
	'@ILBE Assault Pack - Rewrite'
	'@Interiors for CUP'
        '@KAT - Advanced Medical'
	'@RHSAFRF'
	'@RHSGREF'
	'@RHSUSAF'
	'@RHSSAF'
	'@Rosche, Germany'
	'@S7 Compat'
	'@Sling Load Rigging'
	'@Specialist Military Arms (SMA) Version 2.7.1'
	'@Šumava'
	'@SMA Compatibility Fix'
	'@Suppress'
	'@Task Force Arrowhead Radio (BETA!!!)'
	'@US_SOC_LITE_mas'
	'@UMB Colombia'
	'@VSM All-In-One Collection'
	'@VSM - ACE3 Compatibility'
	'@Zeus Enhanced'
	'@Zeus Enhanced - ACE3 Compatibility'
	'@Zulu Headless Client (ZHC)'
        '@Athena - An Arma 2nd Screen Application'
	'@Better Inventory'
	'@Blastcore Murr Edition'
	'@Client''s FPS, Displayed for Zeus'
	'@DUI - Squad Radar'
	'@DynaSound 2'
	'@Enhanced Soundscape'
	'@@Fawks'' Enhanced NVGs'
	'@HMDs - RHS'
	'@HMDs MOD'
        '@HMDs - CUP'
	'@Head Range Plus - TrackIR Mod'
	'@JSRS SOUNDMOD'
	'@JSRS SOUNDMOD - CUP VEHICLES MOD SOUND SUPPORT'
	'@JSRS SOUNDMOD - CUP WEAPONS MOD SOUND SUPPORT'
	'@JSRS SOUNDMOD - RHS  AiO Mod Pack Sound Support'
	'@JSRS SOUNDMOD - SMA Specialst Military Arms Mod Support'
	'@VileHUD'

**Additional context**
[arma3server_x64_2023-11-12_18-59-15.rpt.txt](https://github.com/TMZulu/ZHC/files/13344176/arma3server_x64_2023-11-12_18-59-15.rpt.txt)

**Comment by MildlyInterested** [comment]
This line in the logs might explain it:
```sqf
//line 89194
22:27:20 Error in expression <l {sleep 0.5; (groupOwner _groupMoving) == (zhc_offload_HeadlessIds select _hcIn>
   Error position: <== (zhc_offload_HeadlessIds select _hcIn>
   Error Undefined behavior: waitUntil returned nil. True or false expected.
22:27:20 File t\zhc\addons\offload\fnc_transfer.sqf..., line 82
```

**Comment by SekiAlpha** [comment]
I don't think I edited the blacklist, and there was no disconnect with the headless clients or the main Zeus as IIRC.

The reason why I say IIRC is because I think I was the one who was logged in admin, and I never disconnected. However, I did give Zeus to a few people, although I don't think they would affect the script. The headless clients were all stable though.

If need be I will re-enable ZHC on my unit's servers this Monday and we'll try and recreate the issue.

**Comment by TMZulu** [comment]
@SekiAlpha If you do, and notice that ZHC isnt offloading, then please change verbosity to Verbose and see if you get the checks are still occurring. They will appear in chat if they do.

**Comment by SekiAlpha** [comment]
Okay then, I will try to get you some more data.

**Comment by TMZulu** [comment]
@SekiAlpha if you would be willing to use a dev build for a bit, you can DM me on discord. I am in the Arma discord if you cant DM me directly.

**Comment by jupster** [comment]
Hi, on the latest workshop version.

```
Error in expression <ect _hcIndex)) || (isNull _groupMoving) || zhc_offload_EmergencyTransferring
};
>
   Error position: <|| zhc_offload_EmergencyTransferring
};

>
   Error Undefined behavior: waitUntil returned nil. True or false expected.
18:57:04 In last 10000 miliseconds was lost another 18 these messages.
18:57:04 File t\zhc\addons\offload\fnc_transfer.sqf..., line 119
```

Had this spammed 465 over a 3 hour operation.

Mod's:

KAT, ACE, 3CB_BAF_Vehicles, @Hatchet_Framework__Stable_Version, @Hatchet_H_60_pack__Stable_Version, @CUP_Weapons, @CUP_Vehicles, @CUP_Units, @CUP_Terrains__Maps, @CUP_Terrains__Core, @CUP_ACE3_Compatibility_Addon__Weapons, @CUP_ACE3_Compatibility_Addon__Vehicles, @CUP_ACE3_Compatibility_Addon__Terrains , @Community_Factions_Project_CFP_, CBA, TFAR, @3CB_BAF_Weapons, @RKSL_Studios__Attachments_v3_02, @DUI__Squad_Radar, @Breaching_Charge, @VcomAI_Development_Build, @LAMBS_Danger_fsm & obviously @Zulu_Headless_Client_ZHC_

I'll try and get a RPT to you tomorrow.

**Comment by SekiAlpha** [comment]
Hey I don't have any data unfortunately but during my units Sunday Operations the mod randomly stopped working again. I have no idea why either.

**Comment by TMZulu** [comment]
Well, throw the server RPTs in please. With the added logging in the last updates, it may show something.

**Comment by SekiAlpha** [comment]
I just got a reproduction and logs as well
[arma3server_x64_2023-12-10_21-56-55.zip](https://github.com/TMZulu/ZHC/files/13644511/arma3server_x64_2023-12-10_21-56-55.zip)

I did notice at line 117157 that there were local groups on some HCs but zero local units. I'm not sure if that's expected behavior or not though.

**Comment by TMZulu** [comment]
Well, the v1.1.6 release should fix this as the wait condition that causes this perpetual hang has been moved from the server side processing over to the HC. I will close this issue for now, please reopen it if the issue occurs again.
