### ISSUE TITLE
[BUG] Map markers are spaced incorrectly

### ISSUE THREAD

**Issue by MildlyInterested** [TMZulu/ZHC#43]
![image](https://github.com/TMZulu/ZHC/assets/57712666/5a14f20f-ba7f-43ca-9684-a073713916bd)
There is one HCs even further up on the right, not visible atm.

**Comment by TMZulu** [comment]
This is due to the map size as the markers are spaced at a fixed distance apart. Will look into making it dynamic based on map size.
